### ISSUE TITLE
Keine neuen Daten

### ISSUE THREAD

**Issue by volleybase** [Daniel-Breuss/covid-data-austria#2]
Die letzte AGES Umstellung hat scheinbar die Datenübernahme blockiert, bitte korrigieren.
Kann ich ev. helfen - bin Programmierer.

**Comment by Daniel-Breuss** [comment]
Richtig, die AGES-Umstellung hat mir wieder einiges kaputt gemacht.
Einerseits gibt es keine tagesaktuellen Werte mehr, sondern nur eine Rückschau auf den Vortag. Andererseits fehlt auf einmal das File für die Bezirksdaten, das ich bisher genutzt hatte. 
Habe inzwischen die Umstellung geschafft, die Daten werden weiterhin täglich um 14:05 aktualisiert, aber leider nur eben mit den Daten vom Vortag.
