### ISSUE TITLE
Falsche Daten

### ISSUE THREAD

**Issue by hagi123456** [Daniel-Breuss/covid-data-austria#6]
Am 2021-05-11 dürfte ein Fehler passiert sein. 

Das schaut jetzt so aus: 
 
| Datum  | Fälle_gesamt  | ... |
| -- | -- |  -- |
| 2021-05-12 | 630993  |... |
| 2021-01-11 | 382763 | ... |
| 2021-05-10 | 628714  | ...|

Da sind anstatt der Werte für den 11.5. die Werte vom 11.1 hineingerutscht.

**Comment by Daniel-Breuss** [comment]
Danke für den Hinweis! Sollte mit dem nächsten Update morgen behoben sein. In den Datenbanken selbst passt es, aber an dem Tag musste ich den CSV-Export manuell anwerfen und habe offenbar das falsche Datum eingegeben.
